# Generated by Django 3.1 on 2020-09-12 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_users_city_users_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_user', to='accounts.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users_profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='user_city',
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='users_city',
        ),
        migrations.DeleteModel(
            name='users_profile',
        ),
    ]
