# Generated by Django 3.1 on 2020-08-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vacancy',
        ),
    ]
