# Generated by Django 3.1 on 2020-08-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_auto_20200831_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descriptions',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
